version: '3.8'
services:
  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  app:
    image: photo-share
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/upload


volumes:
  redisData:
